apiVersion: v1
kind: Service
metadata:
  labels:
    app: image-analysis
  name: image-analysis
spec:
  selector:
    app: image-analysis
  ports:
  - name: http
    port: 7788
    protocol: TCP
    targetPort: 9999
